# Generated by Django 4.1 on 2022-08-10 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import paste.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashableMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('trashablemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paste.trashablemixin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=50000)),
                ('expired_at', models.DateTimeField(default=paste.models.get_next_30th_day)),
                ('short_url', models.CharField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('paste.trashablemixin',),
        ),
    ]
